<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Support</title>
  <script src="../Scripts/jquery.min.js" type="text/javascript"></script>
  <script src="../Scripts/jquery-1.7.1.js"></script>
  <script src="../Scripts/jquery.signalR-2.2.0.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="../signalr/hubs"></script>
  <script src="../general/general.js"></script>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="../plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../dist/css/adminlte.min.css">
</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img class="animation__wobble" src="../dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
    </div>
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a id="admin.html" class="nav-link">Home</a>
        </li>
      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
            <form class="form-inline">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                  <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item menu-open pt-3">
              <a id="admin.html" class="nav-link active mb-3">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Pages
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a id="supportView" class="nav-link ">
                    <i class="far fa-circle nav-icon"></i>
                    <p>View Requests</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="changeCategory" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Change Category</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="closeRequest" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Close Request</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="viewConvo" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>View Conversations</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="logout" href="/sda" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Logout</p>
                  </a>
                </li>
              </ul>
            </li>

          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper supportView">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h4 class="loggedname text-right"></h4>
            <h1 class="m-0">View complains</h1>
          </div><!-- /.col -->
          <div class="col-md-3">
            <div class="form-group">
              <label class="mt-2" for="select">Category Fliter</label>
              <select onload=" loadFilter() " onchange="loadTable()" class="form-control " id="selectStatus"
                placeholder="select">
                <option>
                </option>
                <script id="loadStatus" type="text/x-handlebars">
                <option value = "ALL" >All</option>
                {{#each OUTPUT}}
              <option value = "{{SDA_STATUS_ID}}" >{{ SDA_STATUS_NAME}}</option>
              {{/each}}
            </script>
              </select>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="col-md">
            <div class="card card">
              <div class="card-header">
                <h3 class="card-title">View complains</h3>
              </div>
              <div class="card-body">
                <br>
                <div id="displayRequest">

                </div>


              </div>
            </div>
          </div>
        </div>
        <!-- /.content -->
      </div>
  

      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content" id="supportReply">

          </div>
        </div>
      </div>
    </div>
    <!-- handlebar for view  message -->
    <script id="requestTemplate" type="text/x-handlebars">
      <table class="table table-dark pt-5">
        <thead>
          <tr>
            <th scope="col">Customer's Name</th>
            <th scope="col">Email</th>
            <th scope="col">Complain</th>
            <th scope="col">Category</th>
            <th scope="col">Status</th>
            <th scope="col">Date Created</th>
  
          </tr>
        </thead>
        
        <tbody id="tableRow">
          {{#each OUTPUT}}
          
          <tr>
            <td>{{SDA_CUSTOMER_FNAME}}</td>
            <td>{{SDA_CUSTOMER_EMAIL}}</td>
            <td>{{SDA_BODY_TEXT}}</td>
            <td>{{SDA_CATEGORY_NAME}}</td>
            <td>{{SDA_STATUS_NAME}}</td>
            <td>{{formatTime SDA_BODY_DATE_CREATED}}</td>
            <td>
              {{#if (statusCheck SDA_STATUS_NAME)}}
              <button class="btn btn-primary mb-4 modalBtn" onclick="fetchCustomerMesssage('{{SDA_BODY_ID}}')"  data-toggle="modal" data-target="#myModal" data-id="{{SDA_BODY_ID}}">Reply</button>
              {{/if}}
            </td>
          </tr>
            {{/each}}
        </tbody>
      </table>
    </script>

    <!-- Handlebar for supportView -->
    <script id="supportReplyTemp" type="text/x-handlebars">
    {{#with OUTPUT}}



    <div class="modal-header">
      <span> <b>Email:</b> {{SDA_CUSTOMER_EMAIL}}</span>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-header">
      <span> <b>Category:</b> {{SDA_CATEGORY_NAME}} </span>
    </div>
    <div class="modal-header">
      <span> <b>Status:</b> {{SDA_STATUS_NAME}}</span>
    </div>
    <div class="modal-header">
      <span> <b>Date:</b> {{formatTime SDA_BODY_DATE_CREATED}}</span>
      </div>
      <div class="modal-header">
        <p><b>Customer's Message:</b> {{SDA_BODY_TEXT}}</p>
      </div>
    <div class="modal-body">
      <form onsubmit="return false" id="dataForm2">
    <label for="textBody">Support Reply</label>
      <textarea id="textBody" class="form-control"  rows="4" placeholder="Enter reply"></textarea>
    </div> 
    <button id="submit" class="btn btn-primary mb-4" style="width:150px;     margin-left: auto;
    margin-right: auto;" onclick="supportResponding('{{SDA_BODY_ID}}')" data-id="{{SDA_BODY_ID}}">Submit</button>
    </form>
    {{/with}}
</script>


    <div class="content-wrapper  changeCategory" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Change Category</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title">Change Category</h3>
            </div>
            <div class="card-body">
              <div id="supportChange">

              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="modal2" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
              <label for="select"></label>
              <select id="select" class="form-select">
                <option>
                </option>
                <script id="supportChangeCategory" type="text/x-handlebars">
            {{#each OUTPUT}}
            <option value = "{{SDA_CATEGORY_ID}}" >{{ SDA_CATEGORY_NAME}}</option>
            {{/each}}
          </script>
              </select>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" onclick="confirmCategory()"
                data-id="{{SDA_BODY_ID}}">Submit</button>
            </div>
          </div>

        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- handlebar for change category -->
    <script id="supportChangeTable" type="text/x-handlebars">
  <table class="table table-dark pt-5">
    <thead>
      <tr>
        <th scope="col">Customer's Name</th>
        <th scope="col">Email</th>
        <th scope="col">Complain</th>
        <th scope="col">Category</th>
        <th scope="col">Status</th>
        <th scope="col">Date Created</th>

      </tr>
    </thead>
    
    <tbody id="tableRow">
      {{#each OUTPUT}}
      <tr>
        <td>{{SDA_CUSTOMER_FNAME}}</td>
        <td>{{SDA_CUSTOMER_EMAIL}}</td>
        <td>{{SDA_BODY_TEXT}}</td>
        <td>{{SDA_CATEGORY_NAME}}</td>
        <td>{{SDA_STATUS_NAME}}</td>
        <td>{{formatTime SDA_BODY_DATE_CREATED}}</td>
        <td><button class="btn btn-primary mb-4 " data-id="{{SDA_BODY_ID}}" data-toggle="modal" data-target="#modal2" onclick="changeSupportCategory('{{SDA_BODY_ID}}')">Change Category</button></td>
      </tr>
        {{/each}}
    </tbody>
  </table>
</script>

    <div class="content-wrapper closeRequest" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Close Request</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title">Close a request</h3>
            </div>
            <div class="card-body">
              <div id="supportCloseReq">

              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- handlebar for close request -->
    <script id="supportCloseRequest" type="text/x-handlebars">
  <table class="table table-dark pt-5">
    <thead>
      <tr>
        <th scope="col">Customer's Name</th>
        <th scope="col">Email</th>
        <th scope="col">Complain</th>
        <th scope="col">Category</th>
        <th scope="col">Status</th>
        <th scope="col">Date Created</th>

      </tr>
    </thead>
    
    <tbody id="tableRow">
      {{#each OUTPUT}}
      <tr>
        <td>{{SDA_CUSTOMER_FNAME}}</td>
        <td>{{SDA_CUSTOMER_EMAIL}}</td>
        <td>{{SDA_BODY_TEXT}}</td>
        <td>{{SDA_CATEGORY_NAME}}</td>
        <td>{{SDA_STATUS_NAME}}</td>
        <td>{{formatTime SDA_BODY_DATE_CREATED}}</td>
        <td><button class="btn btn-primary mb-4 " onclick="changeComplainStatus('{{SDA_BODY_ID}}')" data-id="{{SDA_BODY_ID}}">Close Request</button></td>
      </tr>
        {{/each}}
    </tbody>
  </table>
</script>



    <div class="content-wrapper viewConvo" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Conversations</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title"> View Chats</h3>
            </div>

            <div class="card-body" id="displayChat">

            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="myModal3" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="supportViewChat">

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>

      <!-- /.content -->
    </div>
    <!-- handlebar for view conversation -->
    <script id="viewChat" type="text/x-handlebars">
  <table class="table table-dark pt-5">
    <thead>
      <tr>
        <th scope="col">Customer's Name</th>
        <th scope="col">Email</th>
        <th scope="col">Status</th>
        <th scope="col">Date Created</th>

      </tr>
    </thead>
    
    <tbody id="tableRow">
      {{#each OUTPUT}}
      <tr>
        <td>{{SDA_CUSTOMER_FNAME}}</td>
        <td>{{SDA_CUSTOMER_EMAIL}}</td>
        <td>{{SDA_STATUS_NAME}}</td>
        <td>{{formatTime SDA_BODY_DATE_CREATED}}</td>
        {{#if (convoChecker SDA_STATUS_NAME)}}
        <td><button class="btn btn-primary mb-4" data-toggle="modal" data-target="#myModal3" onclick="supportChatFunc('{{SDA_BODY_ID}}')" data-id="{{SDA_BODY_ID}}">View Chat</button></td>
        {{/if}}
      </tr>
        {{/each}}
    </tbody>
  </table>
</script>
    <!-- handlebar for modal  -->
    <script id="supportChatHistory" type="text/x-handlebars">

  <div class="card direct-chat direct-chat-primary">
    <div class="card-header">
      <h3 class="card-title">Direct Chat</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  
  <div class="card-body">
    
    <div class="direct-chat-messages">
      {{#with OUTPUT.[0]}}
      <div class="direct-chat-msg">
        <div class="direct-chat-infos clearfix">
          <span class="direct-chat-name float-left">{{SDA_CUSTOMER_FNAME}} (Customer)</span>
          <span class="direct-chat-timestamp float-right">{{formatTime SDA_DATE_CREATED}}</span>
        </div>
        <div class="direct-chat-text">
          {{SDA_BODY_TEXT}}
        </div>
      </div>
      {{/with}}
      {{#each OUTPUT}}
      {{#if (chattype RESPOND_TYPE)}}
      <div class="direct-chat-msg">
      <div class="direct-chat-infos clearfix">
        <span class="direct-chat-name float-left">{{RESPONDER}}</span>
        <span class="direct-chat-timestamp float-right">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
      </div>
      <div class="direct-chat-text">
        {{SUPPORT_REPLY_BODY}}
      </div>
    </div>
    {{else}}

    <div class="direct-chat-msg right">
      <div class="direct-chat-infos clearfix">
        <span class="direct-chat-name float-right">{{RESPONDER}}</span>
        <span class="direct-chat-timestamp float-left">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
      </div>
      <div class="direct-chat-text">
        {{SUPPORT_REPLY_BODY}}
      </div>
    </div>
    {{/if}}
    {{/each}}
  </div>
  <div class="card-footer">
    <form onsubmit="return false" id="dataForm2">
      <div class="input-group">
        <input type="text" name="message" id="adminMessage"  placeholder="Type Message ..." class="form-control">
        <span class="input-group-append">
          <button type="button" class="btn btn-primary" onclick="supportChatting()" >Send</button>
        </span>
      </div>
    </form>
  </div>
  </div>

</div>

</script>


    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- Default to the left -->
      <strong> <a id="supportView">SDA</a>.</strong> All rights reserved.
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <script src="../Scripts/handlebars.js"></script>
  <script src="support.js"></script>
  <!-- jQuery -->
  <script src="../plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="../dist/js/adminlte.min.js"></script>
  <script>
    Handlebars.registerHelper('formatTime', function (date) {
      return new Date(date).toDateString();
    });
    Handlebars.registerHelper('statusCheck', function (value) {
      var b = true;
      if (value != "Pending" && value != "Customer Reply") {
        b = false;
      }
      return b;
    });
    Handlebars.registerHelper('chattype', function (val) {
      return (val == "CUSTOMER") ? 1 : 0;
    });
    Handlebars.registerHelper('convoChecker', function (value) {
      var b = true;
      if (value == "Pending") {
        b = false;
      }
      return b;
    });
  </script>
</body>

</html>