<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin</title>
  <script src="../Scripts/jquery.min.js" type="text/javascript"></script>
  <script src="../Scripts/jquery-1.7.1.js"></script>
  <script src="../Scripts/jquery.signalR-2.2.0.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="../signalr/hubs"></script>
  <script src="../general/general.js"></script>
  <script src="admin.js"></script>
  <link rel="stylesheet" href="../plugins/fontawesome-free/css/all.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="../plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../dist/css/adminlte.min.css">
</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img class="animation__wobble" src="../dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
    </div>
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
            <form class="form-inline" onsubmit="return false" id="form">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Enter mail to search"
                  id="adminSearch" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-navbar" id="searchAdmin" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                  <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a id="admin.html" class="brand-link">
        <img src="../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
          style="opacity: .8">
        <span class="brand-text font-weight-light">Admin</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item menu-open pt-3">
              <a id="admin" class="nav-link active mb-3">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Pages
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a id="dashboard" class="nav-link ">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Dashboard</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a onload="fetchTable()" id="viewRequest" class="nav-link ">
                    <i class="far fa-circle nav-icon"></i>
                    <p>View Requests</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="assignRole" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Assign Role</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="manageRole" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Manage Roles</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="userCategories" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Create Categories</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="closeAdminRequest" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Close Request</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="logout" href="/sda" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Logout</p>
                  </a>
                </li>
              </ul>
            </li>

          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper dashboard">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h4 class="loggedname text-right"></h4>
            <h1 class="m-0">Dashboard</h1>
            <br />
          </div><!-- /.col -->

          <!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg">


              <div class="card card-dark">
                <div class="card-header">
                  <h3 class="card-title">Apllication Details</h3>

                  <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                  </div>
                </div>
                <div class="card-body">
                  <div id="displayResult1" class="col-md">
                  </div>
                  <br />
                  <div id="displayResult2" class="col-md">
                  </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- ./col -->
            </div>
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <script id="adminDash1" type="text/x-handlebars">
      {{#each OUTPUT}}
    <div class="row">
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
          <div class="inner">
            <h3>{{TOTAL_CUSTOMER}}</h3>

            <p>Total Customers</p>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
          <div class="inner">
            <h3>{{TOTAL_SUPPORT}}</h3>

            <p>Total Support</p>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-secondary">
          <div class="inner">
            <h3>{{TOTAL_RATING}}</h3>
  
            <p>Total Rated Chats</p>
          </div>
        </div>
      </div>
  
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-secondary">
          <div class="inner">
            <h3>{{TOTAL_UNRATED}}</h3>
  
            <p>Total Unrated Chats</p>
          </div>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
          <div class="inner">
            <h3>{{TOTAL_ADMIN}}</h3>

            <p>Total Admin</p>
          </div>
        </div>
      </div>
      <!-- ./col -->
    </div>
    {{/each}}
  </script>

    <script id="adminDash2" type="text/x-handlebars">
      {{#each OUTPUT}}
      <div class="row">
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-secondary">
        <div class="inner">
          <h3>{{TOTAL_PENDING}}</h3>

          <p>Total Pending</p>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-info">
        <div class="inner">
          <h3>{{TOTAL_ANSWERED}}</h3>

          <p>Total Answered</p>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-dark">
        <div class="inner">
          <h3>{{TOTAL_SOLVED}}</h3>

          <p>Total Solved</p>
        </div>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
      <!-- small box -->
      <div class="small-box bg-success">
        <div class="inner">
          <h3>{{TOTAL_COMPLAINED}}</h3>

          <p>Total Complained</p>
        </div>
      </div>
    </div>
      {{/each}}
    </script>

    <div class="content-wrapper viewRequest" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h4 class="loggedname text-right"></h4>
            <h1 class="m-0">View Requests</h1>
            <br />

            <button type="button" onclick="resetTable()" class="btn btn-primary">Reset Table</button>
          </div><!-- /.col -->

          <!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg">
              <div class="card">
                <div class="card-body">
                  <h3 class="card-title">Complain History</h3>
                  <br>
                  <br>

                  <div id="display">

                  </div>

                </div>
              </div>


            </div>
            <!-- /.col-md-6 -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

      <div class="modal fade" id="myModal3" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="supportViewChat">

          </div>

        </div>
      </div>

  <!-- Modal -->
  <div class="modal fade" id="myModalProfile" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content" id="displayCustomerProfile">

      </div>

    </div>
  </div>
    </div>
    <!-- handlebar for viewchat Table  -->      
    <script id="viewChat" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Customer's Name</th>
              <th scope="col">Customer's Email</th>
              <th scope="col">Complain</th>
              <th scope="col">Status</th>
              <th scope="col">Category</th>
              <th scope="col">Date Created</th>
            </tr>
          </thead>
          <tbody id="tableRow">
            {{#each OUTPUT}}
          <tr>
            <td>{{SDA_CUSTOMER_FNAME}}</td>
            <td>{{SDA_CUSTOMER_EMAIL}}</td>
            <td>{{SDA_BODY_TEXT}}</td>
            <td>{{SDA_STATUS_NAME}}</td>
            <td>{{SDA_CATEGORY_NAME}}</td>
            <td>{{ formatTime SDA_BODY_DATE_CREATED}}</td>
            {{#if (checkChat SDA_STATUS_NAME)}}
            <td><button class="btn btn-primary mb-4 "data-toggle="modal" data-target="#myModal3" onclick="supportChatFunc('{{SDA_BODY_ID}}')" data-id="{{SDA_BODY_ID}}">View Conversations</button></td>
            {{/if}}
          </tr>
          {{/each}}
          </tbody>
        </table>
      </div>

    </script>
    <!-- handlebar for viewChat modal  -->
    <script id="supportChatHistory" type="text/x-handlebars">

          <div class="card direct-chat direct-chat-primary">
            <div class="card-header">
              <h3 class="card-title">Direct Chat</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        
          
          <div class="card-body">
            
            <div class="direct-chat-messages">
              {{#with OUTPUT.[0]}}
              <div class="direct-chat-msg">
                <div class="direct-chat-infos clearfix">
                  <span class="direct-chat-name float-left">{{SDA_CUSTOMER_FNAME}} (Customer)</span>
                  <span class="direct-chat-timestamp float-right">{{formatTime SDA_DATE_CREATED}}</span>
                </div>
                <div class="direct-chat-text">
                  {{SDA_BODY_TEXT}}
                </div>
              </div>
              {{/with}}
              {{#each OUTPUT}}
              {{#if (chattype RESPOND_TYPE)}}
              <div class="direct-chat-msg">
              <div class="direct-chat-infos clearfix">
                <span class="direct-chat-name float-left">{{RESPONDER}}</span>
                <span class="direct-chat-timestamp float-right">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
              </div>
              <div class="direct-chat-text">
                {{SUPPORT_REPLY_BODY}}
              </div>
            </div>
            {{else}}
        
            <div class="direct-chat-msg right">
              <div class="direct-chat-infos clearfix">
                <span class="direct-chat-name float-right">{{RESPONDER}}</span>
                <span class="direct-chat-timestamp float-left">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
              </div>
              <div class="direct-chat-text">
                {{SUPPORT_REPLY_BODY}}
              </div>
            </div>
            {{/if}}
            {{/each}}
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              {{#with OUTPUT.[0]}}
              <button type="button" class="btn btn-primary" data-toggle="modal" onclick="customerProfileChecker('{{SDA_CUSTOMER_ID}}')" data-customer_id="{{SDA_CUSTOMER_ID}}" data-target="#myModalProfile">View Customer Profile</button>
              {{/with}}
            </div>
          </div>
          </div>
        </div>
        
        </script>
    <!-- handlebar for view Profile modal  -->
    <script id="viewCustomerProfile" type="text/x-handlebars">
      {{#each OUTPUT}}
      <div class="card direct-chat direct-chat-primary">
        <div class="card-header">
          <h3 class="card-title">{{SDA_CUSTOMER_FNAME}}'s Profile</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      
      <div class="card-body">
        <span> Name: {{SDA_CUSTOMER_FNAME}}</span>
        <br/>
        <span> Email {{SDA_CUSTOMER_EMAIL}}</span>
        <br/>
        <span>Total Number of Complains: {{TOTAL_COMPLAINED}}</span>
        <br/>
        <span>Date Profile Created: {{ formatTime SDA_CUSTOMER_DATE_CREATED}}</span>
        <br/>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
    {{/each}}
    </script>

    <div class="content-wrapper assignRole" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Create Page</h1>
          </div><!-- /.col -->
          <!-- <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a id = "admin.html">Home</a></li>
            </ol>
          </div>  -->
          <!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md-8">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title">Assign Role</h3>
            </div>
            <div class="card-body">
              <form onsubmit="return false" class="dataForm">
                <div class="form-group">
                  <label for="inputDescription">Enter Name </label>
                  <input class="form-control mb-2" type="text" name="name" id="name">
                  <label for="inputDescription">Enter password </label>
                  <input class="form-control mb-2" type="password" name="password" id="password">
                  <label for="inputDescription">Enter email </label>
                  <input class="form-control mb-2" type="email" name="email" id="email">
                  <label for="role">Role</label>
                  <select onload="loadSupport()" id="select" placeholder="select" class="form-control displayy">
                    <option>
                    </option>
                    <script id="roleTemplate" type="text/x-handlebars">
                        <option>
                          Assign Role
                        </option>
                        {{#each OUTPUT}}
                        <option value="{{SDA_ROLE_ID}}">{{SDA_ROLE_NAME}}</option>
                        {{/each}}
                      </script>
                  </select>

                  <label class="pt-2" for="role">Category</label>
                  <select onload=" loadFilter() " class="form-control " id="selectStatus" placeholder="select">
                    <option>
                    </option>
                    <script id="loadStatus" type="text/x-handlebars">
                        <option value="">
                          Assign Category
                        </option>
                        {{#each OUTPUT}}
                      <option value = "{{SDA_CATEGORY_ID}}" >{{ SDA_CATEGORY_NAME}}</option>
                      {{/each}}
                    </script>
                  </select>
                </div>
              </form>
              <button id="submitBtn" class="btn btn-dark">Submit</button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>

    <div class="content-wrapper manageRole" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg-6">
            <h1 class="m-2">Manage Role</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Manage Role</h3>
                <br>
                <br>
                <div id="displayRole">

                </div>

              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title">Manage Categories</h3>
                <br>
                <br>
                <div id="displayCat">

                </div>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="myModalAdmin" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="adminProfiler">

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <!-- /.content -->
    </div>
<!-- for delete support -->
    <script id="deleteTemplate" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Role</th>
              <th scope="col">Category</th>
            </tr>
          </thead>
          
          <tbody id="tableRow">
            {{#each OUTPUT}}
            <tr>
              <td>{{SDA_SUPPORT_NAME}}</td>
              <td>{{SDA_ROLE_NAME}}</td>
              <td>{{SDA_CATEGORY_NAME}}</td>
              <td>  <button class="btn btn-danger mb-4 delete" onclick= "deleteInfo('{{SDA_SUPPORT_ID}}')" data-id="{{SDA_SUPPORT_ID}}">Delete</button></td>
              <td>  <button class="btn btn-primary mb-4 " onclick= "viewInfo('{{SDA_SUPPORT_ID}}')" data-id="{{SDA_SUPPORT_ID}}" data-toggle="modal" data-target="#myModalAdmin">View Details</button></td>
            </tr>
              {{/each}}
          </tbody>
        </table>
      </div>

     
    </script>
<!-- for delete category -->
    <script id="fetchCat" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Categories</th>
            </tr>
          </thead>
          
          <tbody id="tableRow">
            {{#each OUTPUT}}
            <tr>
              <td>{{SDA_CATEGORY_NAME}}</td>
              <td>  <button class="btn btn-danger mb-4 delete deletee"   onclick= "deleteCategory('{{SDA_CATEGORY_ID}}')" data-id="{{SDA_CATEGORY_ID}}">Delete</button></td>
            </tr>
              {{/each}}
          </tbody>
        </table>
      </div>
     
    </script>
    <!-- SUPPORT PROFILE -->
    <script id="viewSupportProfile" type="text/x-handlebars">
      {{#each OUTPUT}}
      <div class="card direct-chat direct-chat-primary">
        <div class="card-header">
          <h3 class="card-title">{{SDA_SUPPORT_NAME}}'s Profile</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      
      <div class="card-body">
        <span> Name: {{SDA_SUPPORT_NAME}}</span>
        <br/>
        <span> Email {{SDA_SUPPORT_EMAIL}}</span>
        <br/>
        <span>Support Type: {{SDA_SUPPORT_TYPE}}</span>
        <br/>
        <span>Category Name: {{SDA_CATEGORY_NAME}}</span>
        <br/>
        <span>Role Type: {{SDA_ROLE_NAME}}</span>
        <br/>
        <span>Date Profile Created: {{ formatTime SDA_SUPPORT_DATE_CREATED}}</span>
        <br/>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
    {{/each}}
    </script>

    <div class="content-wrapper userCategories" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Complaint Categories</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md-8">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title">Create Complaint Category</h3>
            </div>
            <div class="card-body">
              <form onsubmit="return false" id="dataForm">
                <div class="form-group">
                  <label for="enterName">Enter Category </label>
                  <input class="form-control mb-2" type="text" placeholder="Enter Complaint Category" id="category">
                </div>
                <button type="submit" class="btn btn-dark submitBtn" id="submit">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>

    <div class="content-wrapper closeAdminRequest" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-lg ">
            <h1 class="m-0">Close Request</h1>
          </div><!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md">
          <div class="card card-dark">
            <div class="card-header">
              <h3 class="card-title">Close a request</h3>
            </div>
            <div class="card-body">
              <div id="adminCloseReq">

              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- handlebar for close request -->
    <script id="adminCloseRequest" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Customer's Name</th>
              <th scope="col">Email</th>
              <th scope="col">Complain</th>
              <th scope="col">Category</th>
              <th scope="col">Status</th>
              <th scope="col">Date Created</th>
      
            </tr>
          </thead>
          
          <tbody id="tableRow">
            {{#each OUTPUT}}
            <tr>
              <td>{{SDA_CUSTOMER_FNAME}}</td>
              <td>{{SDA_CUSTOMER_EMAIL}}</td>
              <td>{{SDA_BODY_TEXT}}</td>
              <td>{{SDA_CATEGORY_NAME}}</td>
              <td>{{SDA_STATUS_NAME}}</td>
              <td>{{formatTime SDA_BODY_DATE_CREATED}}</td>
              <td><button class="btn btn-primary mb-4 " onclick="changeComplainStatus('{{SDA_BODY_ID}}')" data-id="{{SDA_BODY_ID}}">Close Request</button></td>
            </tr>
              {{/each}}
          </tbody>
        </table>
      </div>
  
</script>


    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- Default to the left -->
      <strong> <a id="admin">SDA</a>.</strong> All rights reserved.
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <script src="../Scripts/handlebars.js"></script>
  <!-- jQuery -->
  <script src="../plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="../dist/js/adminlte.min.js"></script>
  <script>
    Handlebars.registerHelper('formatTime', function (date) {
      return new Date(date).toDateString();
    });
    Handlebars.registerHelper('statusCheck', function (value) {
      var b = true;
      if (value != "Pending" && value != "Customer Reply") {
        b = false;
      }
      return b;
    });
    Handlebars.registerHelper('checkChat', function (value) {
      var b = false;
      if (value != "Pending" && value != "Customer Reply") {
        b = true;
      }
      return b;
    });
    Handlebars.registerHelper('chattype', function (val) {
      return (val == "CUSTOMER") ? 1 : 0;
    });
  </script>
</body>

</html>