<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Customer</title>
  <script src="../Scripts/jquery.min.js" type="text/javascript"></script>
  <script src="../Scripts/jquery-1.7.1.js"></script>
  <script src="../Scripts/jquery.signalR-2.2.0.js"></script>
  <!--Reference the autogenerated SignalR hub script. -->
  <script src="../signalr/hubs"></script>
  <!-- <script src="../admin/admin.js"></script> -->
  <script src="customer.js"></script>
  <script src="../general/general.js"></script>
  <link rel="stylesheet" href="styles.css">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="../plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../dist/css/adminlte.min.css">
</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">
    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
      <img class="animation__wobble" src="../dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
    </div>
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">

        </li>
      </ul>

      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
            <form class="form-inline">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                  <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>


      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a class="brand-link">
        <img src="../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
          style="opacity: .8">
        <span class="brand-text font-weight-light">Customer</span>
      </a>

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
            <li class="nav-item menu-open pt-3">
              <a href="customer.aspx" class="nav-link active mb-3">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Pages
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a id="dashboard" class="nav-link ">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Dashboard</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="complaintHistory" class="nav-link ">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Complain History</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="Ratings" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Ratings</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="viewConvo" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>View Conversations</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a id="logout" href="/sda" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Logout</p>
                  </a>
                </li>
              </ul>
            </li>

          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper dashboard">
      <!-- Content Header (Page header) -->
      <div class="content-header justify-content-center">
        <div class="container-fluid">
          <div class="col-md ">
            <h4 class="loggedname text-right"></h4>
            <h1 class="m-0">Complaint Page</h1>
          </div>
          <!-- /.col -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="container-fluid">
        <div class="col-md ">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Complaint</h3>
            </div>
            <div class="card-body">
              <form onsubmit="return false" id="dataForm">
                <div class="form-group">
                  <div class="form-group">
                    <label for="select">Category Fliter</label>
                    <select onload=" loadComplain() " class="form-control displayy" id="select" placeholder="select">
                      <option>
                      </option>
                      <script id="optionTemplate" type="text/x-handlebars">
                        <option>
                          Choose a Category...
                        </option>
                    {{#each OUTPUT}}
                  <option value = "{{SDA_CATEGORY_ID}}" >{{ SDA_CATEGORY_NAME}}</option>
                  {{/each}}
                </script>
                    </select>
                  </div>
                  <label for="textBody">Complaint Description</label>
                  <textarea id="textBody" class="form-control" rows="4"></textarea>
                </div>
              </form>
              <button id="submit" class="btn btn-danger">Submit</button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper complaintHistory" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-3">
              <h1 class="m-0">Complain History </h1>
            </div><!-- /.col -->
            <div class="col-md-3">

              <div class="form-group">
                <label for="select">Category Fliter</label>
                <select onload=" loadFilter() " onchange="loadTable()" class="form-control " id="selectStatus"
                  placeholder="select">
                  <option>
                  </option>
                  <script id="loadStatus" type="text/x-handlebars">
                    <option value="All">
                      All
                    </option>
                    {{#each OUTPUT}}
                  <option value = "{{SDA_STATUS_ID}}" >{{ SDA_STATUS_NAME}}</option>
                  {{/each}}
                </script>
                </select>
              </div>
            </div>
            <!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md">
              <div class="card">
                <div class="card-body">
                  <h3 class="card-title">Complain History</h3>
                  <br>
                  <br>
                  <div id="display">

                  </div>
                  
                </div>
              </div>


            </div>
            <!-- /.col-md-6 -->
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <div class="modal fade" id="myModal4" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="customerReopen">

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- COMPLAIN TEMPLATE -->
    <script id="complainTemplate" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Complain</th>
              <th scope="col">Status</th>
              <th scope="col">Category</th>
              <th scope="col">Date Created</th>
            </tr>
          </thead>
          <tbody id="tableRow">
            {{#each OUTPUT}}
          <tr>
            <td>{{SDA_BODY_TEXT}}</td>
            <td>{{SDA_STATUS_NAME}}</td>
            <td>{{SDA_CATEGORY_NAME}}</td>
            <td>{{ formatTime SDA_BODY_DATE_CREATED}}</td>
            {{#if (checkSolved SDA_STATUS_NAME)}}
            <td><button class="btn btn-primary mb-4 " onclick="reOpenChat('{{SDA_BODY_ID}}')" data-toggle="modal" data-target="#myModal4" data-id="{{SDA_BODY_ID}}">Reopen Chat</button></td>
            {{/if}}
          </tr>
          {{/each}}
          </tbody>
        </table>
  
      </div>
    </script>
    <!-- modal for customer reopen chat -->
    <script id="customerReopenChat" type="text/x-handlebars">

      <div class="card direct-chat direct-chat-primary">
        <div class="card-header">
          <h3 class="card-title">Direct Chat</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    
      
      <div class="card-body">
        
        <div class="direct-chat-messages">
          {{#with OUTPUT.[0]}}
          <div class="direct-chat-msg">
            <div class="direct-chat-infos clearfix">
              <span class="direct-chat-name float-left">{{SDA_CUSTOMER_FNAME}} (Customer)</span>
              <span class="direct-chat-timestamp float-right">{{formatTime SDA_DATE_CREATED}}</span>
            </div>
            <div class="direct-chat-text">
              {{SDA_BODY_TEXT}}
            </div>
          </div>
          {{/with}}
          {{#each OUTPUT}}
          {{#if (chattype RESPOND_TYPE)}}
          <div class="direct-chat-msg">
          <div class="direct-chat-infos clearfix">
            <span class="direct-chat-name float-left">{{RESPONDER}}</span>
            <span class="direct-chat-timestamp float-right">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
          </div>
          <div class="direct-chat-text">
            {{SUPPORT_REPLY_BODY}}
          </div>
        </div>  <!-- end  -->
        {{else}}
    
        <div class="direct-chat-msg right">
          <div class="direct-chat-infos clearfix">
            <span class="direct-chat-name float-right">{{RESPONDER}}</span>
            <span class="direct-chat-timestamp float-left">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
          </div>
          <div class="direct-chat-text">
            {{SUPPORT_REPLY_BODY}}
          </div>
        </div>   <!-- end right -->
        {{/if}}
        {{/each}}
      </div>
      <div class="card-footer">
        <form onsubmit="return false" id="dataForm3">
          <div class="input-group">
            <input type="text" name="message" id="customerMessage2" placeholder="Type Message ..." class="form-control">
            <span class="input-group-append">
              <button type="button" class="btn btn-primary" onclick="customerReplyReopen()" >Send</button>
            </span>
          </div>
        </form>
      </div>
      </div>
    </div>
    
    
    
    
    
        </script>

    <div class="content-wrapper chatHistory" style="display:none">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-3">
              <h1 class="m-0">Chat History </h1>
            </div><!-- /.col -->
            <!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
            <div class="col-md">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Chat History</h3>
                </div>
                <div class="card-body">

                  <div id="chatDisplay">

                  </div>

                </div>
              </div>


            </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="customerViewChat">

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- script to load convo table -->
    <script id="chatTemplate" type="text/x-handlebars">
      <div class="table-responsive">
        
    <table class="table table-dark pt-5">
      <thead>
        <tr>
          <th scope="col">Complain</th>
          <th scope="col">Status</th>
          <th scope="col">Category</th>
          <th scope="col">Date Created</th>
        </tr>
      </thead>
      <tbody id="tableRow">
        {{#each OUTPUT}}
      <tr>
        <td>{{SDA_BODY_TEXT}}</td>
        <td>{{SDA_STATUS_NAME}}</td>
        <td>{{SDA_CATEGORY_NAME}}</td>
        <td>{{ formatTime SDA_BODY_DATE_CREATED}}</td>
        {{#if (checkChatStatus SDA_STATUS_NAME)}}
        <td><button class="btn btn-primary mb-4" onclick="supportChatFunc('{{SDA_BODY_ID}}')" data-toggle="modal" data-target="#myModal" data-id="{{SDA_BODY_ID}}">View Chat</button></td>
        {{/if}}
      </tr>
      {{/each}}
      </tbody>
    </table>
      </div>

  </script>

    <!-- handlebar for modal  -->
    <script id="customerChatHistory" type="text/x-handlebars">

  <div class="card direct-chat direct-chat-primary">
    <div class="card-header">
      <h3 class="card-title">Direct Chat</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  
  <div class="card-body">
    
    <div class="direct-chat-messages">
      {{#with OUTPUT.[0]}}
      <div class="direct-chat-msg">
        <div class="direct-chat-infos clearfix">
          <span class="direct-chat-name float-left">{{SDA_CUSTOMER_FNAME}} (Customer)</span>
          <span class="direct-chat-timestamp float-right">{{formatTime SDA_DATE_CREATED}}</span>
        </div>
        <div class="direct-chat-text">
          {{SDA_BODY_TEXT}}
        </div>
      </div>
      {{/with}}
      {{#each OUTPUT}}
      {{#if (chattype RESPOND_TYPE)}}
      <div class="direct-chat-msg">
      <div class="direct-chat-infos clearfix">
        <span class="direct-chat-name float-left">{{RESPONDER}}</span>
        <span class="direct-chat-timestamp float-right">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
      </div>
      <div class="direct-chat-text">
        {{SUPPORT_REPLY_BODY}}
      </div>
    </div>  <!-- end  -->
    {{else}}

    <div class="direct-chat-msg right">
      <div class="direct-chat-infos clearfix">
        <span class="direct-chat-name float-right">{{RESPONDER}}</span>
        <span class="direct-chat-timestamp float-left">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
      </div>
      <div class="direct-chat-text">
        {{SUPPORT_REPLY_BODY}}
      </div>
    </div>   <!-- end right -->
    {{/if}}
    {{/each}}
  </div>
  <div class="card-footer">
    <form onsubmit="return false" id="dataForm2">
      <div class="input-group">
        <input type="text" name="message" id="customerMessage" placeholder="Type Message ..." class="form-control">
        <span class="input-group-append">
          <button type="button" class="btn btn-primary" onclick="customerReply()" >Send</button>
        </span>
      </div>
    </form>
  </div>
  </div>
</div>





    </script>


    <!-- /.content-wrapper -->
    <div class="content-wrapper Ratings" style="display: none;">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-3">
            <h1 class="m-2">Ratings </h1>
          </div>
        </div>
      </div>
      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md">
              <div class="card">
                <div class="card-body">
                  <h3 class="card-title">Ratings</h3>
                  <br>
                  <br>
                  <div id="chatDisplay2">

                  </div>

                </div>
              </div>


              <!-- /.col-md-6 -->
            </div>
          </div>
          <!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>

      <div class="modal fade" id="myModal2" role="dialog">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content" id="customerViewChat2">

          </div>

        </div>
      </div>




      <!-- /.content -->
    </div>
    <script id="ratingTemplate" type="text/x-handlebars">
      <div class="table-responsive">
        <table class="table table-dark pt-5">
          <thead>
            <tr>
              <th scope="col">Complain</th>
              <th scope="col">Rating</th>
              <th scope="col">Date Created</th>
            </tr>
          </thead>
          <tbody id="tableRow">
            {{#each OUTPUT}}
          <tr>
            <td>{{SUPPORT_REPLY_BODY}}</td>
            <td>{{SDA_RATING_ID}}</td>
            <td>{{ formatTime SUPPORT_REPLY_DATE_CREATED}}</td>
            {{#if (checkChatStatus SDA_STATUS_NAME)}}
            <td><button class="btn btn-primary mb-4" onclick="supportChatFunc('{{SDA_BODY_ID}}')" data-toggle="modal" data-target="#myModal2" data-id="{{SDA_BODY_ID}}">Rate Chat</button></td>
            {{/if}}
          </tr>
          {{/each}}
          </tbody>
        </table>
      </div>
  
    </script>

    <!-- handlebar for modal  -->
    <script id="customerChatHistory2" type="text/x-handlebars">

    <div class="card direct-chat direct-chat-primary">
      <div class="card-header">
        <h3 class="card-title">Direct Chat</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
  
    
    <div class="card-body">
      
      <div class="direct-chat-messages">
        {{#with OUTPUT.[0]}}
        <div class="direct-chat-msg">
          <div class="direct-chat-infos clearfix">
            <span class="direct-chat-name float-left">{{SDA_CUSTOMER_FNAME}} (Customer)</span>
            <span class="direct-chat-timestamp float-right">{{formatTime SDA_DATE_CREATED}}</span>
          </div>
          <div class="direct-chat-text">
            {{SDA_BODY_TEXT}}
          </div>
        </div>
        {{/with}}
        {{#each OUTPUT}}
        {{#if (chattype RESPOND_TYPE)}}
        <div class="direct-chat-msg">
        <div class="direct-chat-infos clearfix">
          <span class="direct-chat-name float-left">{{RESPONDER}}</span>
          <span class="direct-chat-timestamp float-right">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
        </div>
        <div class="direct-chat-text">
          {{SUPPORT_REPLY_BODY}}
        </div>
      </div>  <!-- end  -->
      {{else}}
  
      <div class="direct-chat-msg right">
        <div class="direct-chat-infos clearfix">
          <span class="direct-chat-name float-right">{{RESPONDER}}</span>
          <span class="direct-chat-timestamp float-left">{{formatTime SUPPORT_REPLY_DATE_CREATED}}</span>
        </div>
        <div class="direct-chat-text">
          {{SUPPORT_REPLY_BODY}}
        </div>
      </div>   <!-- end right -->
      {{/if}}
      {{/each}}
    </div>

    <div class="container">
      <div class="starrating risingstar d-flex justify-content-center flex-row-reverse">
        <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="5 star"></label>
        <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="4 star"></label>
        <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="3 star"></label>
        <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="2 star"></label>
        <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="1 star"></label>
      </div>
      <button  class="btn btn-primary " onclick= "submitRating()" id="showStarVal" type="button">Submit Rating</button>
    </div>
    </div>
  </div>
  
  
  
  
  
  </script>

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- Default to the left -->
      <strong> <a href="customer.html">SDA</a>.</strong> All rights reserved.
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <script src="../Scripts/handlebars.js"></script>
  <!-- jQuery -->
  <script src="../plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="../dist/js/adminlte.min.js"></script>
  <!-- handlebar helpers -->
  <script>
    Handlebars.registerHelper('formatTime', function (date) {
      return new Date(date).toDateString();
    });
    Handlebars.registerHelper('checkChatStatus', function (value) {
      var b = true;
      if (value == "Solved" || value == "Pending") {
        b = false;
      }
      return b;
    });
    Handlebars.registerHelper('checkSolved', function (value) {
      var b = false;
      if (value == "Solved") {
        b = true;
      }
      return b;
    });
    Handlebars.registerHelper('chattype', function (val) {
      return (val == "CUSTOMER") ? 1 : 0;
    });
  </script>
</body>

</html>